/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SectorConfig } from '../types';

export const SECTORS: SectorConfig[] = [
  {
    id: 1,
    name: 'Level 1: Deep Nebula',
    codeName: 'LEVEL 1',
    subtitle: 'Calm starry space with drifting asteroids',
    bgGradient: ['#030511', '#0a0d24'],
    nebulaColor: 'rgba(56, 88, 214, 0.12)',
    gridColor: 'rgba(70, 110, 255, 0.04)',
    asteroidSpeedMult: 1.0,
    asteroidSpawnRate: 0.012,
    hazardType: 'none',
    hazardName: 'Calm Space',
    hazardDescription: 'Standard gravity with drifting rocks.',
    wavesCount: 3,
    bossName: 'Vanguard Battleship',
    bossTitle: 'Armored Boss',
  },
  {
    id: 2,
    name: 'Level 2: Electric Storm',
    codeName: 'LEVEL 2',
    subtitle: 'Lightning flashes across dense asteroid clouds',
    bgGradient: ['#021214', '#062024'],
    nebulaColor: 'rgba(20, 184, 166, 0.15)',
    gridColor: 'rgba(45, 212, 191, 0.05)',
    asteroidSpeedMult: 1.35,
    asteroidSpawnRate: 0.02,
    hazardType: 'ionStorm',
    hazardName: 'Lightning Strikes',
    hazardDescription: 'Electric bolts zap across space - avoid the warning flashes!',
    wavesCount: 3,
    bossName: 'Tempest Carrier',
    bossTitle: 'Lightning Boss',
  },
  {
    id: 3,
    name: 'Level 3: Solar Basin',
    codeName: 'LEVEL 3',
    subtitle: 'Blazing star zone with fast asteroids',
    bgGradient: ['#170604', '#260d09'],
    nebulaColor: 'rgba(239, 68, 68, 0.16)',
    gridColor: 'rgba(249, 115, 22, 0.05)',
    asteroidSpeedMult: 1.6,
    asteroidSpawnRate: 0.024,
    hazardType: 'solarFlare',
    hazardName: 'Solar Heatwaves',
    hazardDescription: 'Fiery waves sweep across the screen - dodge or grab a shield!',
    wavesCount: 3,
    bossName: 'Solaris Fortress',
    bossTitle: 'Fire Boss',
  },
  {
    id: 4,
    name: 'Level 4: Black Hole Void',
    codeName: 'LEVEL 4',
    subtitle: 'Swirling gravity vortex pulling all objects',
    bgGradient: ['#0b0217', '#1a082e'],
    nebulaColor: 'rgba(168, 85, 247, 0.18)',
    gridColor: 'rgba(192, 132, 252, 0.06)',
    asteroidSpeedMult: 1.85,
    asteroidSpawnRate: 0.028,
    hazardType: 'blackHole',
    hazardName: 'Black Hole Vortex',
    hazardDescription: 'A central black hole pulls ships and rocks toward the middle!',
    wavesCount: 4,
    bossName: 'Void Colossus',
    bossTitle: 'Final Boss',
  },
];
